### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by arifbalik** [Axolotl-Biosystems/AxoSuite#7]
- [x] Empty Printhead Image
- [x] Printhead Dropdown Calibration button
- [x] Editable workspace location
- [x] Calibration menu implementation
- [x] PorotocolWizard Sanity check
- [x] Tool spesific speed implementation on post process gcode
- [x] BioInk profile
- [x] Status logos on the printhead plates
- [x] Special printhead plates for spesific printheads
